	<div class="login" style="width:550px; height:300px">
      <h1>Success</h1>
     	<p style="text-align:center; margin-top:60px;">
			<span style="font-weight:bold;">Your password has been changed successfully!</span>
        </p>
        <p>
            You may now <a href="login.php">login</a> to the Digital Lab Assistant.<br>
            <br>
            Regards,<br>
            Team Sentinus - Digital Lab Assistant Staff
        </p>
    </div>
